<a href="https://colab.research.google.com/github/stephenbaek/dlcourse/blob/main/assignments/a1_tensorflow_basics.ipynb"><img align="left" src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open in Colab" title="Open and Execute in Google Colaboratory"></a>

# Assignment 1

This is your first homework assignment. Answer the questions below by implementing a TensorFlow code. Please make a copy of this notebook and provide your answers in there.

### Question 1. Import TensorFlow (1 pt)
Write a line to import TensorFlow module with an alias `tf`.

In [ ]:
# PROVIDE YOUR ANSWER HERE

### Question 2-1. (1 pt)
Create two random tensors `x` and `y` of rank 0. The random values should be drawn from uniform distribution.

In [ ]:
# PROVIDE YOUR ANSWER HERE

### Question 2-2. (2 pt)
Define a TensorFlow op that returns `x+y` if `x > y`, and `x*y` otherwise. (Hint: look up `tf.cond()`, `tf.greater()`)

In [ ]:
# PROVIDE YOUR ANSWER HERE

### Question 3-1. (1 pt)

Create a rank 2 tensor `X` of shape `(2, 3)`, whose elements are uniform random values from the range $[-1, 1)$.

In [ ]:
# PROVIDE YOUR ANSWER HERE

### Question 3-2. (2 pt)
Create a rank 2 tensor `Y` with the same shape as `X` above but filled with zeros. (Hint: look up `tf.zeros_like()`)

In [ ]:
# PROVIDE YOUR ANSWER HERE

### Question 3-3. (2 pt)
Return a Boolean tensor that yields `True` if $x_{i,j} < y_{i,j}$.

In [ ]:
# PROVIDE YOUR ANSWER HERE

### Question 3-4. (3 pt)

Get the indices of elements in `X` whose values are greater than 0.2 (Hint: look up `tf.where()`) and then extract those elements (Hint: look up `tf.gather_nd()`).

In [ ]:
# PROVIDE YOUR ANSWER HERE

### Question 4-1. (1 pt)

Create a diagonal matrix (rank 2 tensor) `A` of shape `(10, 10)` whose diagnoal entries are 1, 2, ..., 10. (Hint: `tf.range()` & `tf.diag()`)

In [ ]:
# PROVIDE YOUR ANSWER HERE

### Question 4-2. (2 pt)

Create a matrix by taking the block matrix of shape `(3, 3)` at the top left corner of `A`. (Hint: slicing)

In [ ]:
# PROVIDE YOUR ANSWER HERE

### Question 5. (3 pt)

Create a random 2D tensor of size 15 x 15 from Gaussian distribution $\mathcal{N}(1, 0.5)$ and compute its determinant. (Hint: `tf.random.normal()` & `tf.linalg.det()`)

In [ ]:
# PROVIDE YOUR ANSWER HERE

### Question 6. (2 pt)
Find the unique elements in `x` below. (Hint: tf.unique())

In [ ]:
x = tf.constant([3, 7, 1, 2, 3, 4, 10, 2, 8, 6, 9, 3, 7, 2, 1, 6, 7], dtype=tf.int32)
# PROVIDE YOUR ANSWER HERE

### Question 7-1. (2 pt)

Reshape the tensor `X` below to a `(5,3,2)` tensor.

In [ ]:
X = tf.constant([[0,1,2,3,4,5,6,7,8,9], [10,11,12,13,14,15,16,17,18,19], [20,21,22,23,24,25,26,27,28,29]])
# PROVIDE YOUR ANSWER HERE

### Question 7-2. (3 pt)
Define an operation to reshape tensor `Y` into
```python
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
```

In [ ]:
Y = tf.constant([[1,4,7,10], [2,5,8,11], [3,6,9,12]])
# PROVIDE YOUR ANSWER HERE